#!/usr/bin/env bash

set -uexo pipefail

usage() { echo "Usage: $(basename "$0")"; }
misuse() { usage 1>&2; exit 2; }

test $# -eq 0 || misuse

tmpdir="$(mktemp -d "test-custom-exit-behavior-XXXXXX")"
tmpdir="$(cd "$tmpdir" && pwd)"
trap "$(printf 'rm -rf %q' "$tmpdir")" EXIT

rc=0
./tk -cp "$(pwd)/test" -- \
     -d -b <(echo puppetlabs.trapperkeeper.custom-exit-behavior-test/custom-exit-behavior-test-service) \
     1>"$tmpdir/out" 2>"$tmpdir/err" || rc=$?
cat "$tmpdir/out" "$tmpdir/err"
test "$rc" -eq 7
grep -F 'Some excitement!' "$tmpdir/out"
grep -F 'More excitement!' "$tmpdir/err"
